### ISSUE TITLE
Issue in the output of "enable-plugin export" command

### ISSUE THREAD

**Issue by nyg** [jenv/jenv#392] opened 2023-03-10 22:20 UTC
Hello,

As you can see in the following screenshot, there is a small issue in the output produced by the `jenv enable-plugin export` command:

![jenv-bug](https://user-images.githubusercontent.com/784863/224435517-d0b3391e-4c55-445a-a80d-7bf039df6848.png)

Namely the "echo export plugin activated", which should be "export plugin activated" but on a new line and without the "echo".

I tried to understand what is going on but I don't get it :). `jenv-disalbe-plugin` and `jenv-sh-enable-plugin` seem to be interpreted differently. In the former, there is no usage of "double echo" but in the latter there is.

https://github.com/jenv/jenv/blob/2329e5cb72cc9f25beb8fda4741a2689fd8b8e29/libexec/jenv-disable-plugin#L27

https://github.com/jenv/jenv/blob/2329e5cb72cc9f25beb8fda4741a2689fd8b8e29/libexec/jenv-sh-enable-plugin#L22

Could someone explain what is going on and why it has been done this way?

Thanks,
nyg

**Comment by andrewflbarnes** [comment] 2023-03-13 17:28
`jenv` has a few commands for which it `eval`s any output by the command of which `enable-plugin` is one. You can see this if you take a look at the `jenv` shell function (added by `jenv init -` which is probably `eval`d in your bash profile/rc):
```sh
$ declare -f jenv
jenv ()
{
    type typeset &> /dev/null && typeset command;
    command="$1";
    if [ "$#" -gt 0 ]; then
        shift;
    fi;
    case "$command" in
        enable-plugin | rehash | shell | shell-options)
            eval "`jenv \"sh-$command\" \"$@\"`"
        ;;
        *)
            command jenv "$command" "$@"
        ;;
    esac
}
```

It looks like this is an oversight of when these commands return multiple commands to be `eval`d.

#393 should address this:
```sh
$ jenv disable-plugin export
You may restart your session for removing the jenv export plugin
export disabled

$ jenv enable-plugin export
You may restart your session to activate jenv export plugin
export plugin activated
```

**Comment by nyg** [comment] 2023-03-17 21:09
Thanks for the fix, and the explanation. I noticed this eval vs command also in pyenv, but I'm not sure I understand why it's needed.

**Comment by andrewflbarnes** [comment] 2023-03-20 19:16
No worries :)

As to why it's needed my guess is it allows delaying execution of shell side effects until after a command has completed. For example I think when looking into this, enable plugin actually does something like
```bash
echo "echo blah blah blah && jenv rehash"
```

Doing it this way will guarantee the rehash only runs after the enable plugin has completed in it's entirety.

**Comment by andrewflbarnes** [comment] 2023-10-13 17:45
@nyg - might want to keep this open until #393 is actually merged.

@gcuisinier - any chance this can be merged + released?

**Comment by nyg** [comment] 2023-10-15 09:11
Oops, I thought I was already merged! Thanks.

**Comment by andrewflbarnes** [comment] 2024-03-04 02:29
@Patterner - the problem you're seeing isn't related to this issue which is specific to the output of the command `jenv enable-plugin export`, not whether it's execution is successful.

Try the below and if you are still facing problems, raise a separate issue with steps to reproduce. details of your env, shell, etc.

Check the [getting started section in the readme](https://github.com/jenv/jenv?tab=readme-ov-file#1-getting-started) - it sounds like you're shell isn't initialised correctly.

```
# Shell: bash
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(jenv init -)"' >> ~/.bash_profile
# Shell: zsh
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(jenv init -)"' >> ~/.zshrc
```

> Restart your shell by closing and reopening your terminal window or running exec $SHELL -l in the current session for the changes to take effect.
>
> To verify jenv was installed, run jenv doctor...

**Closed** 2024-03-06 19:02 UTC
