### ISSUE TITLE
`jenv doctor && java -version` will not Output the Java version

### ISSUE THREAD

**Issue by master-bob** [jenv/jenv#390] opened 2023-03-06 16:42 UTC
Hello,

Thanks for making jenv. I think its quite swell.

There appears to be an issue with how `jenv doctor` exits, as in even if everything is "OK" the exit code is still an error. This is using bash.

```Shell
root@2071111a4f98:/project# jenv doctor
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
```
```sh
root@2071111a4f98:/project# jenv doctor; java -version
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)
```
```Bash
root@2071111a4f98:/project# jenv doctor && java -version
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
```
```Sh
root@2071111a4f98:/project# jenv --help
jenv 0.5.5-1-g26f4e81
Usage: jenv <command> [<args>]

Some useful jenv commands are:
   commands    List all available jenv commands
   local       Set or show the local application-specific Java version
   global      Set or show the global Java version
   shell       Set or show the shell-specific Java version
   rehash      Rehash jenv shims (run this after installing executables)
   version     Show the current Java version and its origin
   versions    List all Java versions available to jenv
   which       Display the full path to an executable
   whence      List all Java versions that contain the given executable
   add         Add JDK into jenv. A alias name will be generated by parsing "java -version"

See `jenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/jenv/jenv/blob/master/README.md
```

I would expect `jenv doctor && java -version` to also output the Java version as `jenv doctor; java -version` does when all conditions are "OK".

Please change this behavior, if possible.

**Comment by andrewflbarnes** [comment] 2023-03-08 17:41
Looks like this occurs when no plugins are enabled - should be fixed by #391

**Comment by master-bob** [comment] 2023-03-10 15:10
I can confirm the fix works. :+1: 

My tests:
```Bash
jenv has been updated, process to refresh plugin links
root@4b3963b25606:/project# jenv doctor
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
```
```sh
root@4b3963b25606:/project# jenv doctor; java -version
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-8u352-ga-1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)
```
```sh
root@4b3963b25606:/project# jenv doctor && java -version
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-8u352-ga-1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)
```
```sh
root@4b3963b25606:/project# cd ~/.jenv && git log -n 1
Author: andrewflbarnes <andrewflbarnes@hotmail.co.uk>
Date:   Wed Mar 8 17:32:39 2023 +0000

    Fix jenv doctor exit code when no plugins are enabled
    
    Prevents globbing of JENV_ROOT/plugins/* from resulting in the literal
    string being used when no plugins are present in the folder. This was
    causing jenv doctor to fail resulting in a non-zero exit code.
```

I think the following is outside the scope of this particular issue, but I'm just gonna drop it here as I'm not sure if its working as intended. This is with the fix:
```sh
root@5da3f8496963:/project# jenv doctor; java -version
[ERROR]	JAVA_HOME variable already set, scripts that use it directly could not use java version set by jenv
[OK]	Java binaries in path are jenv shims
[ERROR]	Jenv is not loaded in your bash
[ERROR]	To fix : 	echo eval "$(jenv init -)" >> /root/.bash_profile
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-8u352-ga-1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)
```
```sh
root@5da3f8496963:/project# jenv doctor && java -version
[ERROR]	JAVA_HOME variable already set, scripts that use it directly could not use java version set by jenv
[OK]	Java binaries in path are jenv shims
[ERROR]	Jenv is not loaded in your bash
[ERROR]	To fix : 	echo eval "$(jenv init -)" >> /root/.bash_profile
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-8u352-ga-1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)
```

**Comment by andrewflbarnes** [comment] 2023-03-10 22:40
Glad to hear it's working :)

For the out of scope issue I suspect the intended behaviour is that `jenv doctor` should always return a code of 0 if it _ran_ successfully.

`jenv doctor` finding existing problems is expected behaviour and it means something like below will work as intended
```bash
set -e
set -o pipefail

jenv doctor | grep ERR
```

This might be more of an opinion on my part though so maybe someone else more familiar with jenv can chime in!

**Comment by master-bob** [comment] 2023-03-13 12:14
> I suspect the intended behaviour is that jenv doctor should always return a code of 0 if it ran successfully.

Ahhh, yeah that makes perfect sense.

It completely eliminates the use of `jenv doctor` as a means to programmatically verify that `jenv` has been set up correctly. I think that could be useful for testing. But I could be wrong.

Back on topic, I believe this issue can be closed as soon as the aforementioned PR has been merged. Thank you for your work @andrewflbarnes!

**Closed** 2024-03-06 19:11 UTC
