### ISSUE TITLE
jenv Gives no such a file or directory when run java

### ISSUE THREAD

**Issue by vikumDheemantha** [jenv/jenv#410] opened 2023-06-26 04:03 UTC
I have installed and set up Jenv and it was working well, but somehow recently when I try to run Java command in the terminal I got the following error.

```
/Users/<user_name>/.jenv/shims/java: line 21: /opt/homebrew/Cellar/jenv/0.5.4/libexec/libexec/jenv: No such file or directory
```

I try to change several versions and it does not give errors but when I tried to run Java command it always gives this error. How can I resolve this?

**Comment by harikesh409** [comment] 2023-07-15 18:19
Try running `jenv rehash`. If it gives `.jenv.shim` exists then check the version of jenv installed at `/opt/homebrew/Cellar/jenv` and manually update the version in the `.jenv/shims/java` file.

**Comment by tmendenhall** [comment] 2023-10-11 21:46
Also see https://github.com/jenv/jenv/issues/394

**Comment by andrewflbarnes** [comment] 2024-03-16 16:57
Closing as duplicate of #394

**Closed by andrewflbarnes** 2024-03-16 16:57 UTC
