### ISSUE TITLE
jenv add doesn't add abbreviated aliases for openjdk18

### ISSUE THREAD

**Issue by brampat** [jenv/jenv#373] opened 2022-09-20 13:55 UTC
I've installed openjdk18 through homebrew and added the JDK in jenv:
`jenv add /usr/local/Cellar/openjdk/18.0.2.1/`

However, the available versions in jenv only lists the most specific path for this version, while openjdk17 lists lots more:
`% jenv versions
jenv: version `18' is not installed
  system
  1.8
  1.8.0.292
  10.0
  10.0.2-adoptopenjdk
  12.0
  12.0.1
  17.0
  17.0.3
  18.0.2.1
  openjdk64-1.8.0.292
  openjdk64-10.0.2-adoptopenjdk
  openjdk64-12.0.1
  openjdk64-17.0.3
  openjdk64-18.0.2.1`

How can I manually add version references so I can use `jenv local 18` instead of `jenv local  18.0.2.1`?
Or is there a simpler solution for this?

**Comment by bradleywehmeier** [comment] 2022-09-23 18:46
This looks to be a regression based on the change to the `JAVA_SHORTESTVERSION` from PR 313

**Comment by rofreytag** [comment] 2023-01-30 21:51
having the same issue in my team. seems to be happening on newer versions of jenv.

**Comment by lbilger** [comment] 2023-07-18 09:44
I was also just hit by this issue when setting up my new Mac. I think it's the changed `sed` command from #313. It uses GNU extensions `\+` and `\?` which are not available in `sed` on Mac by default. Haven't checked on Linux, but I guess it probably works there.

Maybe it could be replaced with `sed 's/\([0-9][0-9]*\).*/\1/'`?

**Comment by andrewflbarnes** [comment] 2024-03-13 08:59
0.5.7 has been released where this should be fixed.

**Closed** 2024-03-16 18:07 UTC
