### ISSUE TITLE
regression 0.5.4 to 0.5.5: add doesn't create the shortest alias

### ISSUE THREAD

**Issue by branch-tim** [jenv/jenv#366] opened 2022-06-08 22:50 UTC
On MacOS 12.4, Version 0.5.5 doesn't create the shortest aliases that 0.5.4 did.  Is that intentional or a bug?  It seems like a bug to me.

It's caused by this change in libexec/jenv-add, but I think fixing it is more complicated than reverting that.
```
-    JAVA_SHORTESTVERSION=$(sed 's/\([0-9]\)\..*/\1/' <<< $JAVA_VERSION)
+    JAVA_SHORTESTVERSION=$(sed 's/\([0-9]\+\)\.\?.*/\1/' <<< $JAVA_VERSION)

```

```
$ git status
HEAD detached at 0.5.4
nothing to commit, working tree clean
$ ./bin/jenv add /opt/homebrew/opt/openjdk@17
openjdk64-17.0.3 added
17.0.3 added
17.0 added
17 added

```

```
$ git status
HEAD detached at 0.5.5
nothing to commit, working tree clean
$ ./bin/jenv add /opt/homebrew/opt/openjdk@17
openjdk64-17.0.3 added
17.0.3 added
17.0 added
 17.0.3 already present, skip installation
```

**Comment by DanielThomas** [comment] 2022-06-09 02:18
GNU sed works fine, fails to match with macOS sed. Should work with `-E`.

**Comment by andrewflbarnes** [comment] 2022-08-30 12:43
Just seen this ticket - I had this problem the other week and raised a PR to use compatible BRE:
https://github.com/jenv/jenv/pull/371

**Comment by the-serious-programmer** [comment] 2023-02-17 15:17
@andrewflbarnes @marquiswang #371 has been released in 0.5.6, but unfortunately the issue still exists for me on Mac with homebrew. The shortest version that is created is still 11.0 and 17.0.

Output from my terminal:
```shell
~ % echo $(sed 's/\([0-9]\)\..*/\1/' <<< 17.0)  
17
 ~ % echo $(sed 's/\([0-9]\+\)\.\?.*/\1/' <<< 17.0)  
17.0
~ % echo $(sed 's/\([0-9]\)\..*/\1/' <<< 17.0.0)
17
 ~ % echo $(sed 's/\([0-9]\+\)\.\?.*/\1/' <<< 17.0.0)       
17.0.0
```

As you can see, the old Regex does seem to work for me, while the new one does not.

**Comment by andrewflbarnes** [comment] 2023-02-22 14:50
@the-serious-programmer

Have you confirmed brew has successfully upgraded jenv to `0.5.6` i.e. `jenv --version`?

Looking at the last 3 versions of this sed command:
```bash
# old - 0.5.4 and prior
sed 's/\([0-9]\)\..*/\1/'
# last - 0.5.5
sed 's/\([0-9]\+\)\.\?.*/\1/'
# current - 0.5.6 from #371, not in your output above
sed 's/\([0-9]\{1,\}\)\.\{0,1\}.*/\1/'
```

What output do you get in your terminal with the "current" sed command? e.g.
```bash
sed 's/\([0-9]\{1,\}\)\.\{0,1\}.*/\1/' <<< 17.0
sed 's/\([0-9]\{1,\}\)\.\{0,1\}.*/\1/' <<< 17.0.0
```

If this isn't giving the desired result could you provide some details about the version of sed you're using and confirmed you don't have it aliased/shimmed?

Per [this commit] the change from "old" -> "last" is to account for versions with non numeric suffixes in the java version (e.g. 15-ea) so I don't think it would make sense for jenv to rollback to that version.

[this commit]: https://github.com/jenv/jenv/commit/77303c1727481ee4ff41edf6ef3967f0111cf679

**Comment by andrewflbarnes** [comment] 2023-02-23 02:49
@the-serious-programmer - I've taken a look and while #371 is merged to master, it isn't part of the 0.5.6 release:
https://github.com/jenv/jenv/blob/0.5.6/libexec/jenv-add

Taking a look at the commit graph it was merged in after the creation of 0.5.6:
```bash
git log --decorate --oneline --all --graph
* 2329e5c (HEAD -> master, origin/master, origin/HEAD) Fix jenv-add shortest version for posix and osx
* 703cdc2 Update readme to use cask-versions
* 1518864 (tag: 0.5.6) Prepare 0.5.6
```

So looks like we have to wait for the next version.

**Comment by the-serious-programmer** [comment] 2023-02-23 07:38
Ahh I see, thanks a lot for clarifying that this hasn't been released yet. To avoid confusion in the future it would be nice if there is a changelog highlighting what has been released.

To confirm:
```shell
sed 's/\([0-9]\{1,\}\)\.\{0,1\}.*/\1/' <<< 17.0
sed 's/\([0-9]\{1,\}\)\.\{0,1\}.*/\1/' <<< 17.0.0
```
Does give me the correct output: 17

**Comment by nyg** [comment] 2024-03-13 09:56
Hello @andrewflbarnes, thanks a lot for all the recent work in jenv repository! For CHANGELOG.md, you can have a look at git-cliff. I have no affiliation to it, but use it for one of my repo and I find it quite nice and customisable.

**Comment by andrewflbarnes** [comment] 2024-03-13 14:17
Thanks @nyg - will take a look :)

**Closed** 2024-03-13 14:18 UTC
